baseURL: "https://blog.alarsyo.net/"
title: "Antoine Martin"

defaultContentLanguage: en
defaultContentLanguageInSubdir: false

languages:
  en:
    disabled: false
    languageCode: en-US
    languageName: English
    languageDirection: ltr
    weight: 1


pygmentsCodeFences: true
pygmentsStyle: dracula

enableRobotsTXT: true
